import Head from "next/head";
import styles from "styles/home.module.scss";

export default function Home({ initialUsers }) {
  // https://freefrontend.com/css-book-effects/
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{JSON.stringify(initialUsers)}</main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const response = await fetch("http://localhost:3000/api/users", {
    method: "GET",
    headers: {
      "Content-Type": "application/json; charset=utf8",
    },
  });

  const { users } = await response.json();
  return {
    props: {
      initialUsers: users || [],
    },
  };
};
